library(tibble)
cr <- c(
  "factor(male)0" = "Female",
  "factor(male)1" = "Male",
  "factor(female)0" = "Male",
  "factor(female)1" = "Female",
  "factor(black)0" = "White",
  "factor(black)1" = "Black",
  "factor(white)0" = "Black",
  "factor(white)1" = "White",
  "factor(SIC_Kline)20" = "SIC 20",
  "factor(SIC_Kline)23" = "SIC 23",
  "factor(SIC_Kline)24" = "SIC 24",
  "factor(SIC_Kline)42" = "SIC 42",
  "factor(SIC_Kline)48" = "SIC 48",
  "factor(SIC_Kline)49" = "SIC 49",
  "factor(SIC_Kline)50" = "SIC 50",
  "factor(SIC_Kline)51" = "SIC 51",
  "factor(SIC_Kline)52" = "SIC 52",
  "factor(SIC_Kline)53" = "SIC 53",
  "factor(SIC_Kline)54" = "SIC 54",
  "factor(SIC_Kline)55" = "SIC 55",
  "factor(SIC_Kline)56" = "SIC 56",
  "factor(SIC_Kline)57" = "SIC 57",
  "factor(SIC_Kline)58" = "SIC 58",
  "factor(SIC_Kline)59" = "SIC 59",
  "factor(SIC_Kline)60" = "SIC 60",
  "factor(SIC_Kline)62" = "SIC 62",
  "factor(SIC_Kline)63" = "SIC 63",
  "factor(SIC_Kline)70" = "SIC 70",
  "factor(SIC_Kline)73" = "SIC 73",
  "factor(SIC_Kline)75" = "SIC 75",
  "factor(SIC_Kline)80" = "SIC 80",
  "factor(SIC_Kline)87" = "SIC 87",
  "factor(SIC_Kline)20:factor(male)1" = "SIC 20 × Male",
  "factor(SIC_Kline)23:factor(male)1" = "SIC 23 × Male",
  "factor(SIC_Kline)24:factor(male)1" = "SIC 24 × Male",
  "factor(SIC_Kline)42:factor(male)1" = "SIC 42 × Male",
  "factor(SIC_Kline)48:factor(male)1" = "SIC 48 × Male",
  "factor(SIC_Kline)49:factor(male)1" = "SIC 49 × Male",
  "factor(SIC_Kline)50:factor(male)1" = "SIC 50 × Male",
  "factor(SIC_Kline)51:factor(male)1" = "SIC 51 × Male",
  "factor(SIC_Kline)52:factor(male)1" = "SIC 52 × Male",
  "factor(SIC_Kline)53:factor(male)1" = "SIC 53 × Male",
  "factor(SIC_Kline)54:factor(male)1" = "SIC 54 × Male",
  "factor(SIC_Kline)55:factor(male)1" = "SIC 55 × Male",
  "factor(SIC_Kline)56:factor(male)1" = "SIC 56 × Male",
  "factor(SIC_Kline)57:factor(male)1" = "SIC 57 × Male",
  "factor(SIC_Kline)58:factor(male)1" = "SIC 58 × Male",
  "factor(SIC_Kline)59:factor(male)1" = "SIC 59 × Male",
  "factor(SIC_Kline)60:factor(male)1" = "SIC 60 × Male",
  "factor(SIC_Kline)62:factor(male)1" = "SIC 62 × Male",
  "factor(SIC_Kline)63:factor(male)1" = "SIC 63 × Male",
  "factor(SIC_Kline)70:factor(male)1" = "SIC 70 × Male",
  "factor(SIC_Kline)73:factor(male)1" = "SIC 73 × Male",
  "factor(SIC_Kline)75:factor(male)1" = "SIC 75 × Male",
  "factor(SIC_Kline)80:factor(male)1" = "SIC 80 × Male",
  "factor(SIC_Kline)87:factor(male)1" = "SIC 87 × Male",
  "factor(SIC_Kline)20:factor(male)0" = "SIC 20 × Female",
  "factor(SIC_Kline)23:factor(male)0" = "SIC 23 × Female",
  "factor(SIC_Kline)24:factor(male)0" = "SIC 24 × Female",
  "factor(SIC_Kline)42:factor(male)0" = "SIC 42 × Female",
  "factor(SIC_Kline)48:factor(male)0" = "SIC 48 × Female",
  "factor(SIC_Kline)49:factor(male)0" = "SIC 49 × Female",
  "factor(SIC_Kline)50:factor(male)0" = "SIC 50 × Female",
  "factor(SIC_Kline)51:factor(male)0" = "SIC 51 × Female",
  "factor(SIC_Kline)52:factor(male)0" = "SIC 52 × Female",
  "factor(SIC_Kline)53:factor(male)0" = "SIC 53 × Female",
  "factor(SIC_Kline)54:factor(male)0" = "SIC 54 × Female",
  "factor(SIC_Kline)55:factor(male)0" = "SIC 55 × Female",
  "factor(SIC_Kline)56:factor(male)0" = "SIC 56 × Female",
  "factor(SIC_Kline)57:factor(male)0" = "SIC 57 × Female",
  "factor(SIC_Kline)58:factor(male)0" = "SIC 58 × Female",
  "factor(SIC_Kline)59:factor(male)0" = "SIC 59 × Female",
  "factor(SIC_Kline)60:factor(male)0" = "SIC 60 × Female",
  "factor(SIC_Kline)62:factor(male)0" = "SIC 62 × Female",
  "factor(SIC_Kline)63:factor(male)0" = "SIC 63 × Female",
  "factor(SIC_Kline)70:factor(male)0" = "SIC 70 × Female",
  "factor(SIC_Kline)73:factor(male)0" = "SIC 73 × Female",
  "factor(SIC_Kline)75:factor(male)0" = "SIC 75 × Female",
  "factor(SIC_Kline)80:factor(male)0" = "SIC 80 × Female",
  "factor(SIC_Kline)87:factor(male)0" = "SIC 87 × Female",
  "factor(male)1:factor(SIC_Kline)20" = "Male × SIC 20",
  "factor(male)1:factor(SIC_Kline)23" = "Male × SIC 23",
  "factor(male)1:factor(SIC_Kline)24" = "Male × SIC 24",
  "factor(male)1:factor(SIC_Kline)42" = "Male × SIC 42",
  "factor(male)1:factor(SIC_Kline)48" = "Male × SIC 48",
  "factor(male)1:factor(SIC_Kline)49" = "Male × SIC 49",
  "factor(male)1:factor(SIC_Kline)50" = "Male × SIC 50",
  "factor(male)1:factor(SIC_Kline)51" = "Male × SIC 51",
  "factor(male)1:factor(SIC_Kline)52" = "Male × SIC 52",
  "factor(male)1:factor(SIC_Kline)53" = "Male × SIC 53",
  "factor(male)1:factor(SIC_Kline)54" = "Male × SIC 54",
  "factor(male)1:factor(SIC_Kline)55" = "Male × SIC 55",
  "factor(male)1:factor(SIC_Kline)56" = "Male × SIC 56",
  "factor(male)1:factor(SIC_Kline)57" = "Male × SIC 57",
  "factor(male)1:factor(SIC_Kline)58" = "Male × SIC 58",
  "factor(male)1:factor(SIC_Kline)59" = "Male × SIC 59",
  "factor(male)1:factor(SIC_Kline)60" = "Male × SIC 60",
  "factor(male)1:factor(SIC_Kline)62" = "Male × SIC 62",
  "factor(male)1:factor(SIC_Kline)63" = "Male × SIC 63",
  "factor(male)1:factor(SIC_Kline)70" = "Male × SIC 70",
  "factor(male)1:factor(SIC_Kline)73" = "Male × SIC 73",
  "factor(male)1:factor(SIC_Kline)75" = "Male × SIC 75",
  "factor(male)1:factor(SIC_Kline)80" = "Male × SIC 80",
  "factor(male)1:factor(SIC_Kline)87" = "Male × SIC 87",
  "factor(male)0:factor(SIC_Kline)20" = "Female × SIC 20",
  "factor(male)0:factor(SIC_Kline)23" = "Female × SIC 23",
  "factor(male)0:factor(SIC_Kline)24" = "Female × SIC 24",
  "factor(male)0:factor(SIC_Kline)42" = "Female × SIC 42",
  "factor(male)0:factor(SIC_Kline)48" = "Female × SIC 48",
  "factor(male)0:factor(SIC_Kline)49" = "Female × SIC 49",
  "factor(male)0:factor(SIC_Kline)50" = "Female × SIC 50",
  "factor(male)0:factor(SIC_Kline)51" = "Female × SIC 51",
  "factor(male)0:factor(SIC_Kline)52" = "Female × SIC 52",
  "factor(male)0:factor(SIC_Kline)53" = "Female × SIC 53",
  "factor(male)0:factor(SIC_Kline)54" = "Female × SIC 54",
  "factor(male)0:factor(SIC_Kline)55" = "Female × SIC 55",
  "factor(male)0:factor(SIC_Kline)56" = "Female × SIC 56",
  "factor(male)0:factor(SIC_Kline)57" = "Female × SIC 57",
  "factor(male)0:factor(SIC_Kline)58" = "Female × SIC 58",
  "factor(male)0:factor(SIC_Kline)59" = "Female × SIC 59",
  "factor(male)0:factor(SIC_Kline)60" = "Female × SIC 60",
  "factor(male)0:factor(SIC_Kline)62" = "Female × SIC 62",
  "factor(male)0:factor(SIC_Kline)63" = "Female × SIC 63",
  "factor(male)0:factor(SIC_Kline)70" = "Female × SIC 70",
  "factor(male)0:factor(SIC_Kline)73" = "Female × SIC 73",
  "factor(male)0:factor(SIC_Kline)75" = "Female × SIC 75",
  "factor(male)0:factor(SIC_Kline)80" = "Female × SIC 80",
  "factor(male)0:factor(SIC_Kline)87" = "Female × SIC 87",
  "pct_female:factor(black)1" = "Female share × Black",
  "pct_female:factor(black)0" = "Female share × White",
  "pct_female:factor(white)1" = "Female share × White",
  "pct_female:factor(white)0" = "Female share × Black",
  "age" = "Age",
  "I(age^2)" = "$\\mathrm{Age}^2$",
  "(Intercept)" = "Constant",
  "pct_female" = "Female share",
  "pct_black" = "Black share",
  "black" = "Black",
  "female" = "Female",
  "over40" = "Over 40",
  "lgbtq_club" = "LGBTQ club",
  "academic_club" = "Academic club",
  "political_club" = "Political club",
  "gender_neutral_pronouns" = "Gender-neutral pronouns",
  "same_gender_pronouns" = "Same-gender pronouns",
  "associates" = "Associate degree",
  "wave_1" = "Wave 1",
  "wave_2" = "Wave 2",
  "wave_3" = "Wave 3",
  "wave_4" = "Wave 4",
  "wave_5" = "Wave 5",
  "wave::1" = "Wave 1",
  "wave::2" = "Wave 2",
  "wave::3" = "Wave 3",
  "wave::4" = "Wave 4",
  "wave::5" = "Wave 5",
  "region4::1" = "Northeast",
  "region4::2" = "Midwest",
  "region4::3" = "South",
  "region4::4" = "West",
  "cb" = "Any contact in 30 days",
  "call_cb" = "Voicemail",
  "email_cb" = "Email",
  "text_cb" = "Text",
  "any_cb_0_14" = "Any contact in 14 days",
  "any_cb_15_30" = "Any contact in 15-30 days",
  "wage_gap" = "Wage Gap",
  "state" = "State",
  "soc3" = "SOC3"
)

gm <- tribble(~raw, ~clean, ~fmt,
              "Mean.DV." , "Outcome Mean", 4,
              "nobs", "N", 0,
              #"r.squared", "$\\mathrm{R}^2$", 3,
              "r2.within", "Within $\\mathrm{R}^2$", 3,
              "FE: soc3", "SOC3 FE", 0,
              "FE: educ", "Education FE", 0,
              "FE: year", "Year FE", 0,
              "FE: occ2010", "Occupation FE", 0,
              "FE: state", "State FE", 0,
              "FE: wave", "Wave FE", 0)

glance_custom.fixest <- function(x, ...) {
  out <- data.frame("Mean(DV)" = as.numeric(fitstat(x, type = "my")))
  return(out)
}